const body = document.querySelector("body");
const main = document.createElement("main");
const container = document.createElement("div");
const controlContainer = document.createElement("div");
const h1 = document.createElement("h1");
const buttonContainer = document.createElement("div");
const buttonStart = document.createElement("button");
const buttonStop = document.createElement("button");
const movesDivCreate = document.createElement("div");
const volume = document.createElement("div");
const timerDiv = document.createElement("div");
const fieldSelection = document.createElement("div");
const buttonThree = document.createElement("button");
const buttonFour = document.createElement("button");
const buttonFife = document.createElement("button");
const buttonSix = document.createElement("button");
const buttonSeven = document.createElement("button");
const buttonEight = document.createElement("button");

const gameOverBackground = document.createElement("div");
const gameOverPopUp = document.createElement("div");
const popUpCloseButton = document.createElement("span");
const h2 = document.createElement("h2");

createPanelControl();

function createPanelControl() {
  h1.innerHTML = "Gem Puzzle";
  movesDivCreate.classList = "moves";
  movesDivCreate.textContent = `Moves: 0`;
  volume.classList = "volume";
  volume.classList.add("mute");
  timerDiv.className = "timer-display";
  timerDiv.textContent = "00 : 00 : 00";
  buttonContainer.classList = "button-container stop";
  buttonStart.classList = "button-start start";
  buttonStart.innerHTML = "start";
  buttonStop.classList = "button-stop display-none";
  buttonStop.innerHTML = "pause";
  controlContainer.classList = "control-container";
  controlContainer.append(movesDivCreate);
  controlContainer.append(volume);
  controlContainer.append(timerDiv);
  buttonContainer.append(buttonStart);
  buttonContainer.append(buttonStop);
  container.classList = "container";
  fieldSelection.classList = "field-selection";
  buttonThree.classList = "button-three";
  buttonThree.textContent = `3 X 3`;
  buttonFour.classList = "button-four active";
  buttonFour.textContent = `4 X 4`;
  buttonFife.classList = "button-fife";
  buttonFife.textContent = `5 X 5`;
  buttonSix.classList = "button-six";
  buttonSix.textContent = `6 X 6`;
  buttonSeven.classList = "button-seven";
  buttonSeven.textContent = `7 X 7`;
  buttonEight.classList = "button-eight";
  buttonEight.textContent = `8 X 8`;
  popUpCloseButton.classList = "pop-up-close-button";
  gameOverPopUp.classList = "game-over-pop-up";
  gameOverBackground.classList = "game-over-background";
  fieldSelection.append(buttonThree);
  fieldSelection.append(buttonFour);
  fieldSelection.append(buttonFife);
  fieldSelection.append(buttonSix);
  fieldSelection.append(buttonSeven);
  fieldSelection.append(buttonEight);

  main.append(h1);
  main.append(controlContainer);
  main.append(container);
  main.append(fieldSelection);
  main.append(buttonContainer);
  gameOverPopUp.append(popUpCloseButton);
  gameOverPopUp.append(h2);
  gameOverBackground.append(gameOverPopUp);
  body.append(main);
  body.append(gameOverBackground);
}
